/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialEdge: typeof import('./src/components/SpecialEdge.vue')['default']
    SpecialNode: typeof import('./src/components/SpecialNode.vue')['default']
    TechProgressBar: typeof import('./src/components/TechProgressBar.vue')['default']
    TechSquareBarChart: typeof import('./src/components/TechSquareBarChart.vue')['default']
  }
}
