import { BasicColumn } from '/@/components/Table';
import { FormSchema } from '/@/components/Table';

export const columns: BasicColumn[] = [
		{
			title: '主键',
			dataIndex: 'id',
			width: 100,
			edit: true,
			editComponent: 'Input',
		},
		{
			title: '创建人',
			dataIndex: 'createByName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '创建人',
			dataIndex: 'createBy',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '创建时间',
			dataIndex: 'createDate',
			width: 100,
			edit: false,
			editComponent: 'DatePicker',
		},
		{
			title: '修改人',
			dataIndex: 'updateByName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '修改人',
			dataIndex: 'updateBy',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '修改时间',
			dataIndex: 'updateDate',
			width: 100,
			edit: false,
			editComponent: 'DatePicker',
		},
		{
			title: '站点ID',
			dataIndex: 'siteId',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '创建部门',
			dataIndex: 'createDept',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '创建部门',
			dataIndex: 'createDeptName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '创建公司',
			dataIndex: 'createCompany',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '创建公司',
			dataIndex: 'createCompanyName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '危化品id',
			dataIndex: 'chemicalId',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '危化品name',
			dataIndex: 'chemicalName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: 'un号',
			dataIndex: 'unNo',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '别名',
			dataIndex: 'chemicalAlias',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '英文名',
			dataIndex: 'chemicalEnglish',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: 'cas号',
			dataIndex: 'chemicalCas',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '危险性类别',
			dataIndex: 'chemicalCategory',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '备注',
			dataIndex: 'chemicalRemark',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '状态',
			dataIndex: 'status',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '物品编号',
			dataIndex: 'chemicalNo',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '制造商或供货商名称',
			dataIndex: 'manufacturerName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '制造商或供货商地址',
			dataIndex: 'manufacturerAddress',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '制造商或供货商电话',
			dataIndex: 'manufacturerContact',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '紧急联络电话',
			dataIndex: 'emergencyContact',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '传真',
			dataIndex: 'fax',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '部门领导id',
			dataIndex: 'deptHeadId',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '部门领导name',
			dataIndex: 'deptHeadName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '生产技术部门id',
			dataIndex: 'productionDeptHeadId',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '生产技术部门name',
			dataIndex: 'productionDeptHeadName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '安全环保监督管理部门id',
			dataIndex: 'anDeptHeadId',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '安全环保监督管理部门name',
			dataIndex: 'anDeptHeadName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '总工程师或生产副总经理id',
			dataIndex: 'engineerId',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
		{
			title: '总工程师或生产副总经理name',
			dataIndex: 'engineerName',
			width: 100,
			edit: false,
			editComponent: 'Input',
		},
];

export const searchFormSchema: FormSchema[] = [
		{
			field: '主键',
			label: 'id',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '创建人',
			label: 'createByName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '创建人',
			label: 'createBy',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '创建时间',
			label: 'createDate',
			component: 'DatePicker',
			colProps: { span: 8 },
		},
		{
			field: '修改人',
			label: 'updateByName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '修改人',
			label: 'updateBy',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '修改时间',
			label: 'updateDate',
			component: 'DatePicker',
			colProps: { span: 8 },
		},
		{
			field: '站点ID',
			label: 'siteId',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '创建部门',
			label: 'createDept',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '创建部门',
			label: 'createDeptName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '创建公司',
			label: 'createCompany',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '创建公司',
			label: 'createCompanyName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '危化品id',
			label: 'chemicalId',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '危化品name',
			label: 'chemicalName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: 'un号',
			label: 'unNo',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '别名',
			label: 'chemicalAlias',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '英文名',
			label: 'chemicalEnglish',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: 'cas号',
			label: 'chemicalCas',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '危险性类别',
			label: 'chemicalCategory',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '备注',
			label: 'chemicalRemark',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '状态',
			label: 'status',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '物品编号',
			label: 'chemicalNo',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '制造商或供货商名称',
			label: 'manufacturerName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '制造商或供货商地址',
			label: 'manufacturerAddress',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '制造商或供货商电话',
			label: 'manufacturerContact',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '紧急联络电话',
			label: 'emergencyContact',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '传真',
			label: 'fax',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '部门领导id',
			label: 'deptHeadId',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '部门领导name',
			label: 'deptHeadName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '生产技术部门id',
			label: 'productionDeptHeadId',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '生产技术部门name',
			label: 'productionDeptHeadName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '安全环保监督管理部门id',
			label: 'anDeptHeadId',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '安全环保监督管理部门name',
			label: 'anDeptHeadName',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '总工程师或生产副总经理id',
			label: 'engineerId',
			component: 'Input',
			colProps: { span: 8 },
		},
		{
			field: '总工程师或生产副总经理name',
			label: 'engineerName',
			component: 'Input',
			colProps: { span: 8 },
		},
];

export const formSchema: FormSchema[] = [
            {
                field: 'id',
                label: 'id',
                component: 'Input',
                required: false,
                show: false,
                defaultValue: null,
            },
			{
				field: '创建人',
				label: 'createByName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: true },
			},
			{
				field: '创建人',
				label: 'createBy',
				component: 'Input',
				required: false,
				componentProps: { readOnly: true },
			},
			{
				field: '创建时间',
				label: 'createDate',
				component: 'DatePicker',
				required: false,
				componentProps: { readOnly: true },
			},
			{
				field: '修改人',
				label: 'updateByName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: true },
			},
			{
				field: '修改人',
				label: 'updateBy',
				component: 'Input',
				required: false,
				componentProps: { readOnly: true },
			},
			{
				field: '修改时间',
				label: 'updateDate',
				component: 'DatePicker',
				required: false,
				componentProps: { readOnly: true },
			},
			{
				field: '站点ID',
				label: 'siteId',
				component: 'Input',
				required: false,
				componentProps: { readOnly: true },
			},
			{
				field: '创建部门',
				label: 'createDept',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '创建部门',
				label: 'createDeptName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '创建公司',
				label: 'createCompany',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '创建公司',
				label: 'createCompanyName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '危化品id',
				label: 'chemicalId',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '危化品name',
				label: 'chemicalName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: 'un号',
				label: 'unNo',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '别名',
				label: 'chemicalAlias',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '英文名',
				label: 'chemicalEnglish',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: 'cas号',
				label: 'chemicalCas',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '危险性类别',
				label: 'chemicalCategory',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '备注',
				label: 'chemicalRemark',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '状态',
				label: 'status',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '物品编号',
				label: 'chemicalNo',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '制造商或供货商名称',
				label: 'manufacturerName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '制造商或供货商地址',
				label: 'manufacturerAddress',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '制造商或供货商电话',
				label: 'manufacturerContact',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '紧急联络电话',
				label: 'emergencyContact',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '传真',
				label: 'fax',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '部门领导id',
				label: 'deptHeadId',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '部门领导name',
				label: 'deptHeadName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '生产技术部门id',
				label: 'productionDeptHeadId',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '生产技术部门name',
				label: 'productionDeptHeadName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '安全环保监督管理部门id',
				label: 'anDeptHeadId',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '安全环保监督管理部门name',
				label: 'anDeptHeadName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '总工程师或生产副总经理id',
				label: 'engineerId',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
			{
				field: '总工程师或生产副总经理name',
				label: 'engineerName',
				component: 'Input',
				required: false,
				componentProps: { readOnly: false },
			},
];